app/__init__.py
#!/usr/bin/env python3
# -- coding:utf-8 --
# @Author: markushammered@gmail.com
# @Development Tool: PyCharm
# @Create Time: 2022/3/25
# @File Name: __init__.py


import os
from flask import Flask
from flask_sslify import SSLify
from .main import main as main_blueprint
from .api import api as api_blueprint
from .config import config
from .utils.password import generate_pwd


def create_app(config_name):
    """
    创建 app
    :param config_name:
    :return:
    """
    app = Flask(__name__)
    app.config.from_object(config[config_name])
    config[config_name].init_app(app)
    if app.config['SSL_REDIRECT']:
        SSLify(app)

    app.register_blueprint(main_blueprint)
    app.register_blueprint(api_blueprint, url_prefix='/api/v1/')

    access_key = os.getenv('ACCESS_KEY')
    secret = app.config['SECRET_KEY']
    try:
        if not access_key and not secret:
            access_key = generate_pwd(16)
        elif not access_key and secret:
            access_key = secret
    finally:
        os.environ['ACCESS_KEY'] = access_key

    app.logger.info('访问密钥: {}'.format(access_key))

    return app


__all__ = [
    'db',
    'main',
    'tests',
    'utils',
    'create_app'
]

app/api/__init__.py
#!/usr/bin/env python3
# -- coding:utf-8 --
# @Author: markushammered@gmail.com
# @Development Tool: PyCharm
# @Create Time: 2022/4/9
# @File Name: __init__.py.py


from flask import Blueprint

api = Blueprint('api', __name__)

from . import views, errors

__all__ = [
    'api',
    'views',
    'errors'
]

app/api/auth.py
#!/usr/bin/env python3
# -- coding:utf-8 --
# @Author: markushammered@gmail.com
# @Development Tool: Pycharm
# @Create Time: 2022/5/2
# @File Name: auth.py


import os
from flask import request
from flask_httpauth import HTTPTokenAuth

auth = HTTPTokenAuth()


@auth.verify_token
def verify_token(token):
    secret_key = os.getenv('ACCESS_KEY')
    key = request.args.get('key')
    if token or key == secret_key:
        return True
    elif (token == 'unittest' or
          key == 'unittest') and \
            'system' in request.path.split('/'):  # 限定在system这个接口使用unittest密钥获取数据
        return True
    return False

app/api/views.py
#!/usr/bin/env python3
# -- coding:utf-8 --
# @Author: markushammered@gmail.com
# @Development Tool: PyCharm
# @Create Time: 2022/4/9
# @File Name: views.py


import sys
import psutil
import platform
from flask import jsonify
from flask import request
from flask import send_file
from ..db.db import SQLite as db
from . import api
from .auth import auth


@api.route('/test/', methods=['GET', 'POST'])
def test_api():
    """
    测试专用接口
    :return:
    """
    data = db().fetch('test-example')
    return str(data[1])


@api.route('/overall/', methods=['GET', 'POST'])
def overall():
    """
    查询ReqCount表内所有的源数据
    :return:
    """
    limit = request.args.get('limit', type=int)
    try:
        data = db().exec('select * from reqcount;')
        format_data = []
        for i in data:
            format_data.append({'name': i[0], 'times': i[1]})
        return jsonify(
            {
                'code': 200,
                'msg': 'Success. Total: %s row(s)' % len(data),
                'data': format_data[:limit]
            }
        ), 200
    except Exception as e:
        return jsonify(
            {
                'code': -200,
                'msg': 'Error',
                'data': e
            }
        ), 500


@api.route('/query/', methods=['GET', 'POST'])
def query():
    """
    查询指定名称的计数数据
    :return:
    """
    name = request.args.get('name', type=str)
    nochange = request.args.get('nochange', type=bool)
    if nochange:
        nochange = True
    if not db().exists_name(name):
        return jsonify(
            {
                'code': -200,
                'msg': 'Failed. No such name',
                'data': None
            }
        ), 404
    else:
        data = db().fetch(name, nochange)
        return jsonify(
            {
                'code': 200,
                'msg': 'Success',
                'data': data
            }
        ), 200


@api.route('/theme/', methods=['GET', 'POST'])
def theme():
    """
    查询数据库内主题的源数据
    :return:
    """
    _theme = request.args.get('name', type=str)
    if not db().exists_table(_theme):
        return jsonify(
            {
                'code': 404,
                'msg': 'Failed. No such theme',
                'data': None
            }
        ), 404
    else:
        data = db().fetching_table(_theme)
        return jsonify(
            {
                'code': 200,
                'msg': 'Success',
                'data': data
            }
        ), 200


@api.route('/alltables/', methods=['GET', 'POST'])
def all_tables():
    """
    查询所有已有表
    :return:
    """
    data = db().show_tables
    return jsonify(
        {
            'code': 200,
            'msg': 'Success',
            'data': data
        }
    ), 200


@api.route('/export/', methods=['GET', 'POST'])
@auth.login_required
def export():
    """
    导出数据库文件
    :return:
    """
    return send_file('./db/data.sqlite', as_attachment=True), 200


@api.route('/system/', methods=['GET', 'POST'])
@auth.login_required
def system_info():
    """
    获取当前部署服务器的系统状态信息
    :return:
    """
    _platform = platform.system()
    _cpu_count = psutil.cpu_count()
    _memory_size = psutil.virtual_memory()
    _total_memory_size = round(_memory_size[0] / 1024 / 1024 / 1024, 2)
    _free_memory_size = round(_memory_size[4] / 1024 / 1024 / 1024, 2)
    _used_memory_size = round(_memory_size[3] / 1024 / 1024 / 1024, 2)
    _percent = _memory_size[2]
    _py_version = sys.version

    return jsonify(
        {
            'code': 200,
            'msg': 'Success',
            'data': {
                'Platform': _platform,
                'CPU-Count': _cpu_count,
                'Memory-Size(GigaBytes)': {
                    'Total': _total_memory_size,
                    'used': _used_memory_size,
                    'Free': _free_memory_size,
                    'Percent': _percent
                },
                'Python': _py_version
            }
        }
    ), 200

app/db/__init__.py
#!/usr/bin/env python3
# -- coding:utf-8 --
# @Author: markushammered@gmail.com
# @Development Tool: PyCharm
# @Create Time: 2022/3/25
# @File Name: __init__.py.py


import os
import sys
import requests


def download():
    res = requests.get('https://filebase.vercel.app/download/data.sqlite')
    with open('./app/db/data.sqlite', 'wb') as fp:
        fp.write(res.content)


if not os.path.exists('./app/db/data.sqlite'):
    try:
        download()
    except requests.exceptions as error:
        sys.exit(1)

__all__ = [
    'db'
]

app/main/__init__.py
#!/usr/bin/env python3
# -- coding:utf-8 --
# @Author: markushammered@gmail.com
# @Development Tool: PyCharm
# @Create Time: 2022/3/25
# @File Name: __init__.py.py


from flask import Blueprint

main = Blueprint('main', __name__)

from . import views, errors

__all__ = [
    'main',
    'views',
    'errors'
]

app/main/views.py
#!/usr/bin/env python3
# -- coding:utf-8 --
# @Author: markushammered@gmail.com
# @Development Tool: PyCharm
# @Create Time: 2022/3/25
# @File Name: views.py


from flask import abort
from flask import request
from flask import make_response
from flask import render_template
from ..db.db import SQLite as db
from ..utils.response import index_
from . import main


@main.route('/', methods=['GET', 'POST'])
def index():
    """
    主页
    :return:
    """
    return render_template('index.html', remote_address=request.remote_addr)


@main.route('/count/<string:name>', methods=['GET', 'POST'])
def home(name: str):
    """
    主视图
    :param name:
    :return:
    """
    length = request.args.get('length', 7, type=int)
    theme = request.args.get('theme', 'lewd', type=str)
    if not db().exists_name(name):
        db().insert(name)
    if not db().exists_table(theme):
        abort(500)
    if 7 <= length <= 10:
        data = db().fetch(name)
        if len(str(data[1])) >= 10:  # 计数的数据长度超过最大位数将次数设为1
            db().update(name, 0)
        # 使用设置的长度减去已有数据的长度, 将结果转换为string类型, 再和数据库内的数据进行拼接
        number = '0' * (length - len(str(data[-1]))) + str(data[-1])
        response = make_response(index_(theme, int(length), name, number))
        response.headers['Content-Type'] = 'image/svg+xml; charset=utf-8'
        response.headers['cache-control'] = 'max-age=0, no-cache, no-store, must-revalidate'
        return response
    return abort(500)

app/utils/__init__.py
#!/usr/bin/env python3
# -- coding:utf-8 --
# @Author: markushammered@gmail.com
# @Development Tool: PyCharm
# @Create Time: 2022/3/25
# @File Name: __init__.py.py

__all__ = [
    'response',
    'password'
]

app/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Request Counter | {{ remote_address }}</title>
    <link href="{{ url_for('static', filename='favicon.ico') }}" rel="shortcut icon">
    <link rel="stylesheet" href="{{ url_for('static', filename='index.css') }}">
    <script type="text/javascript" src="{{ url_for('static', filename='request.js') }}"></script>
</head>
<body>
<div class="intro">
    <div class="current_deployment_test">
        <i><a href="{{ url_for('main.home', name='test-example') }}">点击查看当前实例调用示例</a></i>
    </div>
    <div class="remote_deployment_test">
        <i><a href="https://requestcounter.herokuapp.com/count/test-example">点击查看已部署好的调用示例</a></i>
    </div>
    <div class="note">
        <i><b>注: 调用支持POST 和 GET 方法请求</b></i>
    </div>
    <div class="open_source_protocol">
        <i>项目开源协议: <b>Apache-2.0</b> 即:
            <br>
            你可以直接使用该项目提供的功能, 无需任何授权
            <br>
            你可以在注明来源版权信息的情况下对源代码进行任意分发和修改以及衍生
        </i>
    </div>
    <div class="documents">
        <div class="vercel">
            <i><a href="https://request-counter-docs.vercel.app/#/" target="_blank">点击查看托管在<i>Vercel</i>上的文档</a></i>
        </div>
        <div class="github">
            <i><a href="https://markusjoe.github.io/RequestCounter/" target="_blank">点击查看托管在<i>GitHub</i>上的文档</a></i>
        </div>
    </div>
    <div class="ip_address">
        <i><b>请求地址来源: {{ remote_address }}</b></i>
    </div>
</div>
<div class="example">
    <div class="svg">
        <img src="https://static-file-hosting.vercel.app/static/lewd/6" alt="fast_test_example_svg">
        <img src="https://static-file-hosting.vercel.app/static/lewd/1" alt="fast_test_example_svg">
        <img src="https://static-file-hosting.vercel.app/static/lewd/5" alt="fast_test_example_svg">
        <img src="https://static-file-hosting.vercel.app/static/lewd/9" alt="fast_test_example_svg">
        <img src="https://static-file-hosting.vercel.app/static/lewd/0" alt="fast_test_example_svg">
        <img src="https://static-file-hosting.vercel.app/static/lewd/3" alt="fast_test_example_svg">
        <img src="https://static-file-hosting.vercel.app/static/lewd/7" alt="fast_test_example_svg">
        <img src="https://static-file-hosting.vercel.app/static/lewd/8" alt="fast_test_example_svg">
        <img src="https://static-file-hosting.vercel.app/static/lewd/2" alt="fast_test_example_svg">
        <img src="https://static-file-hosting.vercel.app/static/lewd/4" alt="fast_test_example_svg">
    </div>
    <div class="api">
        <button onclick="request_async()">点击获取计数数值</button>
        <div class="result">
            <i><b>test-example</b>当前计数数据值: </i>
            <p id="fast_test_example_text"></p>
        </div>
    </div>
</div>
</body>
</html>

app/templates/view.html
<?xml version="1.0" encoding="UTF-8"?>
<svg width="{{ general_width }}" height="{{ general_height }}" version="1.1" xmlns="http://www.w3.org/2000/svg"
     xmlns:xlink="http://www.w3.org/1999/xlink">
    <title>{{ title }} | {{ address }}</title>
    <g>
        {% for value in context %}
            <image x="{{ value.position }}" y="0" width="{{ value.width }}" height="{{ value.height }}"
                   xlink:href="{{ value.url }}"></image>
        {% endfor %}
    </g>
</svg>